services:
  leetcode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leetcode
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - leetcode-network
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: leetcode

networks:
  leetcode-network:
    driver: bridge
